<a href="https://colab.research.google.com/github/Polyakri/projects/blob/main/ANN/Artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [184]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [185]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [186]:
dataset  = pd.read_csv ('Churn_Modelling.csv')
x = dataset.iloc [:,3:-1].values
y = dataset.iloc [:,-1].values


In [187]:
print(dataset)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMemb

In [188]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [189]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [190]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
x[:,2] = label_encoder.fit_transform(x[:,2])

In [191]:
print (x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [192]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [ ('encoder',OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [193]:
print(x[:10])

[[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]
 [0.0 0.0 1.0 608 0 41 1 83807.86 1 0 1 112542.58]
 [1.0 0.0 0.0 502 0 42 8 159660.8 3 1 0 113931.57]
 [1.0 0.0 0.0 699 0 39 1 0.0 2 0 0 93826.63]
 [0.0 0.0 1.0 850 0 43 2 125510.82 1 1 1 79084.1]
 [0.0 0.0 1.0 645 1 44 8 113755.78 2 1 0 149756.71]
 [1.0 0.0 0.0 822 1 50 7 0.0 2 1 1 10062.8]
 [0.0 1.0 0.0 376 0 29 4 115046.74 4 1 0 119346.88]
 [1.0 0.0 0.0 501 1 44 4 142051.07 2 0 1 74940.5]
 [1.0 0.0 0.0 684 1 27 2 134603.88 1 1 1 71725.73]]


### Splitting the dataset into the Training set and Test set

In [194]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y , test_size =0.2, random_state = 0)

In [195]:
print (x_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [196]:
print (x_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [197]:
print (y_train)

[0 0 0 ... 0 0 1]


In [198]:
print (y_test)

[0 1 0 ... 0 0 0]


### Feature Scaling

In [216]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler ()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [217]:
ann = tf.keras.models.Sequential ()

### Adding the input layer and the first hidden layer

In [218]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))


### Adding the second hidden layer

In [219]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))


### Adding the output layer

In [220]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

## Part 3 - Training the ANN

### Compiling the ANN

In [221]:
ann.compile(optimizer='adam' , loss='binary_crossentropy' , metrics= ['accuracy'])

### Training the ANN on the Training set

In [222]:
ann.fit (x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5879 - accuracy: 0.7189
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4689 - accuracy: 0.7975
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4512 - accuracy: 0.8025
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4395 - accuracy: 0.8056
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4318 - accuracy: 0.8102
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4258 - accuracy: 0.8119
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4212 - accuracy: 0.8145
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4172 - accuracy: 0.8156
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4133 - accuracy: 0.8186
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4093 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [223]:

print( ann.predict(sc.fit_transform(np.array([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))>0.5)

1/1 [==============================] - 0s 90ms/step
[[False]]


**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [224]:
y_pred = ann.predict(x_test)
y_pred = (y_pred >0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis=1))


63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [225]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix( y_test, y_pred)
print(cm)
print (accuracy_score (y_test, y_pred))

[[1515   80]
 [ 199  206]]
0.8605
